// Define action types
export const SAVE_RUNNING = 'SAVE_RUNNING';
export const REMOVE_RUNNING = 'REMOVE_RUNNING';
export const UPDATE_RUNNING = 'UPDATE_RUNNING';
export const SET_GOALDISTANCE = 'SET_GOALDISTANCE';
export const SET_GOALINTERVAL = 'SET_GOALINTERVAL';
export const SET_START_DATE = 'SET_START_DATE'
export const SET_IS_RUNNING = 'SET_IS_RUNNING'
export const SAVE_CURRENTRUNNING = 'SAVE_CURRENTRUNNING';