// Define action types
export const SAVE_RUNNING = 'SAVE_RUNNING';
export const REMOVE_RUNNING = 'REMOVE_RUNNING';
export const UPDATE_RUNNING = 'UPDATE_RUNNING';
export const SET_DISTANCE = 'SET_DISTANCE';
export const SET_INTERVAL = 'SET_INTERVAL';
export const SET_START_DATE = 'SET_START_DATE'
export const SET_IS_RUNNING = 'SET_IS_RUNNING'
export const SAVE_CURRENTRUNNING = 'SAVE_CURRENTRUNNING';